app = "botislav-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  APP_ENV = "production"
  LOG_LEVEL = "info"
  LOG_CHANNEL = "stdout"
  LOG_STDERR_FORMATTER = "Monolog"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  processes = ["app"]
  protocol = "tcp"
