name: Fly Deploy
on: [push]

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            flyctl secrets set DISCORD_TOKEN=$DISCORD_TOKEN
            flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
            DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}